---
  - name: Install prerequisites
    apt: name={{ item }} state=present force=yes
    loop:
      - python3
      - python3-setuptools
      - python3-dev
      - build-essential
      - python3-pip
      - python3-mysqldb
      - git